### ISSUE TITLE
当打开在这里下载的APP的时候都会出现报错

### ISSUE THREAD

**Issue by howyea** [MarnoDev/react-native-open-project#2]
下面是APP报错的内容
 UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): NotFoundError: Cannot find entry file index.android.js in any of the roots: ["D:\\personal\\pro\\ImClient\\node_modules\\.0.42.3@react-native","D:\\personal\\pro\\ImClient\\node_modules\\.1.0.3@abab","D:\\personal\\pro\\ImClient\\node_modules\\.0.0.0@absolute-path","D:\\personal\\pro\\ImClient\\node_modules\\.1.3.3@accepts","D:\\personal\\pro\\ImClient\\node_modules\\.5.0.3@acorn","D:\\personal\\pro\\ImClient\\node_modules\\.3.1

请问这个问题要怎么解决

**Comment by MarnoDev** [comment]
因为版本兼容的问题，RN 版本更新太快了，没有办法，可以考虑把核心代码拷贝出来，放到自己新建的一个项目中试一下。
